services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - type: bind
        source: ./ESGI-theme-maleaume
        target: /var/www/html/wp-content/themes/ESGI-theme-maleaume
      - type: bind
        source: ./ESGI-theme-prof
        target: /var/www/html/wp-content/themes/ESGI-theme-prof
      - type: bind
        source: ./ESGI-theme-tibo
        target: /var/www/html/wp-content/themes/ESGI-theme-tibo


volumes:
  db_data: {}
  wordpress_data: {}
